import forms from "@tailwindcss/forms"
import typography from "@tailwindcss/typography"
import pagination from '@tailwindcss/pagination';
import aspectRatio from "@tailwindcss/aspect-ratio"

const defaultTheme = require("tailwindcss/defaultTheme")
const colors = require("tailwindcss/colors")

export default {
  darkMode: "class",
  content: [
    "./*.{html,js}",
    "./build/**/*.{html,js}",
    "./components/**/*.{html,js}",
    "./pages/**/*.{html,js}",
    "./public/index.html",
    "./src/**/*.{html,js}",
    "./*/*.css",
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    "./storage/framework/views/*.php",
    "./resources/views/**/*.blade.php",
    "./resources/css/**/*.css",
    "./resources/views/vendor/pagination/*.blade.php",
    "./node_modules/@my-company/tailwind-components/**/*.js",
  ],
  theme: {
    screens: {
      sm: "576px",
      "sm-max": { max: "576px" },
      md: "768px",
      "md-max": { max: "768px" },
      lg: "992px",
      "lg-max": { max: "992px" },
      xl: "1200px",
      "xl-max": { max: "1200px" },
      "2xl": "1320px",
      "2xl-max": { max: "1320px" },
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      mine: {
        DEFAULT: "#292929",
        light: "#1a202c",
        lighter: "#525252",
        dark: "#666666",
        darker: "#7B7B7B",
        900: "#181818",
      },
      pirate: {
        DEFAULT: "#936403",
        light: "#936403",
        lighter: "#CA8A04",
        dark: "#FBC34D",
        darker: "#FBB625",
      },
      royal: {
        DEFAULT: "#4A7EEE",
        light: "#4A7EEE",
        lighter: "#2563EB",
        dark: "#95B3F5",
        darker: "#7098F2",
        700: "#2d3748",
        800: "#445c94",
        900: "#21314E",
      },
      white: {
        DEFAULT: "#FFFFFF",
        light: "#ABABAB",
        lighter: "#8F8F8F",
        dark: "#E3E3E3",
        darker: "#C7C7C7",
      },
      success: {
        DEFAULT: "#73F7B6",
        light: "#73F7B6",
        lighter: "#0EEC7F",
        dark: "#C0FBDE",
        darker: "#9AF9CA",
      },
      warning: {
        DEFAULT: "#B3EF49",
        light: "#B3EF49",
        lighter: "#C8F37C",
        dark: "#DEF8B0",
        darker: "#D2F694",
      },
      danger: {
        DEFAULT: "#DD2F7C",
        light: "#DD2F7C",
        lighter: "#E5609B",
        dark: "#F3B3CF",
        darker: "#ED90B9",
      },
      info: {
        DEFAULT: "#7E55F8",
        light: "#7E55F8",
        lighter: "#A78BFA",
        dark: "#E2D9FD",
        darker: "#C5B2FC",
      },
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      DEFAULT: "0.25rem",
      DEFAULT: "4px",
      md: "0.375rem",
      lg: "0.5rem",
      full: "9999px",
      large: "0.75rem",
      large: "12px",
    },
    fontFamily: {
      sans: ["Montserrat", "sans-serif"],
    },
    extend: {
      spacing: {
        "1/2": "50%",
        "1/3": "33.333333%",
        "2/3": "66.666667%",
        "1/4": "25%",
        "2/4": "50%",
        "3/4": "75%",
        "1/5": "20%",
        "2/5": "40%",
        "3/5": "60%",
        "4/5": "80%",
        "1/6": "16.666667%",
        "2/6": "33.333333%",
        "3/6": "50%",
        "4/6": "66.666667%",
        "5/6": "83.333333%",
        "1/12": "8.333333%",
        "2/12": "16.666667%",
        "3/12": "25%",
        "4/12": "33.333333%",
        "5/12": "41.666667%",
        "6/12": "50%",
        "7/12": "58.333333%",
        "8/12": "66.666667%",
        "9/12": "75%",
        "10/12": "83.333333%",
        "11/12": "91.666667%",
      },
      animationDelay: {
        275: "275ms",
        5000: "5s",
      },
      animationDuration: {
        2000: "2s",
        long: "10s",
        "very-long": "20s",
      },
      backgroundOpacity: {
        5: "0.05",
        20: "0.20",
        95: "0.95",
      },
      backgroundSize: {
        "size-200": "200% 200%",
      },
      backgroundPosition: {
        "pos-0": "0% 0%",
        "pos-100": "100% 100%",
      },
      borderRadius: {
        xl: "0.75rem",
      },
      opacity: {
        5: ".05",
        20: ".20",
      },
      spacing: {
        128: "32rem",
        144: "36rem",
      },
      width: {
        128: "32rem",
      },
    },
    variants: {
      extend: {
        keyframes: {
          displace: {
            "0%": { transform: "rotate(0deg)" },
            "20%": { transform: "rotate(-90deg)" },
            "40%": { transform: "rotate(0deg)" },
            "60%": { transform: "rotate(0deg)" },
            "80%": { transform: "rotate(90deg)" },
            "100%": { transform: "rotate(0deg)" },
          },
        },
        backgroundOpacity: ["active"],
        backgroundColor: ["active"],
        fontWeight: ["hover"],
        textOpacity: ["dark"],
        opacity: ["dark"],
        overflow: ["hover"],
        animationDelay: {
          275: "275ms",
          5000: "5s",
        },
        animationDuration: {
          2000: "2s",
          long: "10s",
          "very-long": "20s",
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("tailwindcss-typography")({
      ellipsis: true,
      hyphens: true,
      kerning: true,
      textUnset: true,
      componentPrefix: "c-",
    }),
  ],
  corePlugins: {
    container: false,
  },
}